/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error-dim': '#791903',
        'on-background': '#3b3125',
        'primary-dim': '#7b4700',
        'on-secondary-fixed-variant': '#435f6d',
        'on-surface-variant': '#695d50',
        'on-primary-fixed': '#271300',
        'tertiary-container': '#ffb99f',
        'on-secondary-fixed': '#264350',
        'secondary': '#466370',
        'surface': '#fff8f4',
        'outline': '#86786a',
        'error-container': '#fd795a',
        'surface-dim': '#e8d7c6',
        'tertiary-fixed': '#ffb99f',
        'on-secondary-container': '#395663',
        'on-secondary': '#f3faff',
        'secondary-dim': '#3a5764',
        'surface-container-high': '#f5e6d6',
        'on-primary-container': '#4a2800',
        'on-tertiary-fixed': '#4c2211',
        'surface-container': '#fbebdd',
        'on-tertiary': '#fff7f5',
        'secondary-fixed': '#c9e7f7',
        'on-primary-fixed-variant': '#563000',
        'inverse-surface': '#120d08',
        'inverse-primary': '#ff9800',
        'surface-variant': '#f1e0ce',
        'surface-container-lowest': '#ffffff',
        'background': '#fff8f4',
        'primary-fixed-dim': '#ec8c00',
        'on-surface': '#3b3125',
        'tertiary-dim': '#784632',
        'surface-container-highest': '#f1e0ce',
        'on-tertiary-fixed-variant': '#6f3e2a',
        'outline-variant': '#bfaf9f',
        'secondary-fixed-dim': '#bbd9e9',
        'primary': '#8c5100',
        'inverse-on-surface': '#a59b92',
        'surface-container-low': '#fff1e5',
        'primary-container': '#ff9800',
        'on-error': '#fff7f6',
        'error': '#a73b21',
        'on-error-container': '#6e1400',
        'tertiary': '#86523d',
        'secondary-container': '#c9e7f7',
        'primary-fixed': '#ff9800',
        'on-tertiary-container': '#643622',
        'tertiary-fixed-dim': '#efac92',
        'on-primary': '#fff7f4',
        'surface-tint': '#8c5100',
        'surface-bright': '#fff8f4'
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'Noto Sans SC', 'sans-serif'],
        'body': ['Inter', 'Noto Sans SC', 'sans-serif'],
        'label': ['Inter', 'Noto Sans SC', 'sans-serif'],
        'mono': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace']
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
        'sm': '0.125rem',
        'md': '0.375rem'
      },
      boxShadow: {
        'ambient': '0 8px 32px rgba(59, 49, 37, 0.06)',
        'sticky-up': '0 -4px 12px rgba(0, 0, 0, 0.05)',
      }
    },
  },
  plugins: [],
}
